-- Standardize + complete the country list. Production only ever had the
-- original 9-country seed set (a "small set to start with," per seed.sql's
-- own comment); local dev had grown to the full ~230-country list over past
-- sessions but with an inconsistent mix of alpha-2 (32 countries, matching
-- the original seed) and alpha-3 (198 countries) codes -- exactly the
-- confusion the user hit doing a real data import ("not sure is the
-- country code"). Standardizes everything on ISO 3166-1 alpha-2 (2-letter),
-- matching what the original 9-country seed already used, so nothing
-- already-referenced (existing Exhibitor/Agent/Company records) breaks.
--
-- Order matters: insert every alpha-2 target row FIRST (so old alpha-3 and
-- new alpha-2 rows briefly coexist), THEN repoint any child row still on
-- an old alpha-3 code, THEN delete the now-unreferenced alpha-3 rows --
-- country_code has NO ACTION on update/delete, so doing this in the
-- opposite order fails immediately with an FK violation the moment a
-- child (or the delete) points at a code that doesn't exist yet/still
-- exists. On production (no alpha-3 rows, no exhibitors yet) the
-- repoint/delete steps are no-ops and only the initial INSERT does
-- anything.
INSERT INTO countries (code, name) VALUES
    ('AF', 'Afghanistan'),
    ('AL', 'Albania'),
    ('DZ', 'Algeria'),
    ('AS', 'American Samoa'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AI', 'Anguilla'),
    ('AG', 'Antigua And Barbuda'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AW', 'Aruba'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaijan'),
    ('BS', 'Bahamas'),
    ('BH', 'Bahrain'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BY', 'Belarus'),
    ('BE', 'Belgium'),
    ('BZ', 'Belize'),
    ('BJ', 'Benin'),
    ('BM', 'Bermuda'),
    ('BT', 'Bhutan'),
    ('BO', 'Bolivia'),
    ('BA', 'Bosnia And Herzegovina'),
    ('BW', 'Botswana'),
    ('BR', 'Brazil'),
    ('VG', 'British Virgin Islands'),
    ('BN', 'Brunei'),
    ('BG', 'Bulgaria'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('CV', 'Cabo Verde'),
    ('KH', 'Cambodia'),
    ('CM', 'Cameroon'),
    ('CA', 'Canada'),
    ('KY', 'Cayman Islands'),
    ('CF', 'Central African Republic'),
    ('TD', 'Chad'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CO', 'Colombia'),
    ('KM', 'Comoros'),
    ('CG', 'Congo'),
    ('CK', 'Cook Islands'),
    ('CR', 'Costa Rica'),
    ('CI', 'Côte D''Ivoire'),
    ('HR', 'Croatia'),
    ('CU', 'Cuba'),
    ('CW', 'Curaçao'),
    ('CY', 'Cyprus'),
    ('CZ', 'Czech Republic (Czechia)'),
    ('DK', 'Denmark'),
    ('DJ', 'Djibouti'),
    ('DM', 'Dominica'),
    ('DO', 'Dominican Republic'),
    ('CD', 'Dr Congo'),
    ('EC', 'Ecuador'),
    ('EG', 'Egypt'),
    ('SV', 'El Salvador'),
    ('GQ', 'Equatorial Guinea'),
    ('ER', 'Eritrea'),
    ('EE', 'Estonia'),
    ('SZ', 'Eswatini'),
    ('ET', 'Ethiopia'),
    ('FO', 'Faeroe Islands'),
    ('FK', 'Falkland Islands'),
    ('FJ', 'Fiji'),
    ('FI', 'Finland'),
    ('FR', 'France'),
    ('PF', 'French Polynesia'),
    ('GA', 'Gabon'),
    ('GM', 'Gambia'),
    ('GE', 'Georgia'),
    ('DE', 'Germany'),
    ('GH', 'Ghana'),
    ('GI', 'Gibraltar'),
    ('GR', 'Greece'),
    ('GL', 'Greenland'),
    ('GD', 'Grenada'),
    ('GU', 'Guam'),
    ('GT', 'Guatemala'),
    ('GN', 'Guinea'),
    ('GW', 'Guinea-Bissau'),
    ('GY', 'Guyana'),
    ('HT', 'Haiti'),
    ('VA', 'Holy See'),
    ('HN', 'Honduras'),
    ('HK', 'Hong Kong'),
    ('HU', 'Hungary'),
    ('IS', 'Iceland'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IR', 'Iran'),
    ('IQ', 'Iraq'),
    ('IE', 'Ireland'),
    ('IM', 'Isle Of Man'),
    ('IL', 'Israel'),
    ('IT', 'Italy'),
    ('JM', 'Jamaica'),
    ('JP', 'Japan'),
    ('JO', 'Jordan'),
    ('KZ', 'Kazakhstan'),
    ('KE', 'Kenya'),
    ('KI', 'Kiribati'),
    ('KW', 'Kuwait'),
    ('KG', 'Kyrgyzstan'),
    ('LA', 'Laos'),
    ('LV', 'Latvia'),
    ('LB', 'Lebanon'),
    ('LS', 'Lesotho'),
    ('LR', 'Liberia'),
    ('LY', 'Libya'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('MO', 'Macao'),
    ('MG', 'Madagascar'),
    ('MW', 'Malawi'),
    ('MY', 'Malaysia'),
    ('MV', 'Maldives'),
    ('ML', 'Mali'),
    ('MT', 'Malta'),
    ('MH', 'Marshall Islands'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauritius'),
    ('YT', 'Mayotte'),
    ('MX', 'Mexico'),
    ('FM', 'Micronesia'),
    ('MD', 'Moldova'),
    ('MC', 'Monaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MS', 'Montserrat'),
    ('MA', 'Morocco'),
    ('MZ', 'Mozambique'),
    ('MM', 'Myanmar'),
    ('NA', 'Namibia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NL', 'Netherlands'),
    ('NC', 'New Caledonia'),
    ('NZ', 'New Zealand'),
    ('NI', 'Nicaragua'),
    ('NE', 'Niger'),
    ('NG', 'Nigeria'),
    ('NU', 'Niue'),
    ('KP', 'North Korea'),
    ('MK', 'North Macedonia'),
    ('MP', 'Northern Mariana Islands'),
    ('NO', 'Norway'),
    ('OM', 'Oman'),
    ('PK', 'Pakistan'),
    ('PW', 'Palau'),
    ('PA', 'Panama'),
    ('PG', 'Papua New Guinea'),
    ('PY', 'Paraguay'),
    ('PE', 'Peru'),
    ('PH', 'Philippines'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('PR', 'Puerto Rico'),
    ('QA', 'Qatar'),
    ('RE', 'Réunion'),
    ('RO', 'Romania'),
    ('RU', 'Russia'),
    ('RW', 'Rwanda'),
    ('BL', 'Saint Barthelemy'),
    ('SH', 'Saint Helena'),
    ('KN', 'Saint Kitts & Nevis'),
    ('LC', 'Saint Lucia'),
    ('MF', 'Saint Martin'),
    ('PM', 'Saint Pierre & Miquelon'),
    ('WS', 'Samoa'),
    ('SM', 'San Marino'),
    ('ST', 'Sao Tome & Principe'),
    ('SA', 'Saudi Arabia'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('SL', 'Sierra Leone'),
    ('SG', 'Singapore'),
    ('SX', 'Sint Maarten'),
    ('SK', 'Slovakia'),
    ('SI', 'Slovenia'),
    ('SB', 'Solomon Islands'),
    ('SO', 'Somalia'),
    ('ZA', 'South Africa'),
    ('KR', 'South Korea'),
    ('SS', 'South Sudan'),
    ('ES', 'Spain'),
    ('LK', 'Sri Lanka'),
    ('VC', 'St. Vincent & Grenadines'),
    ('PS', 'State Of Palestine'),
    ('SD', 'Sudan'),
    ('SR', 'Suriname'),
    ('SE', 'Sweden'),
    ('CH', 'Switzerland'),
    ('SY', 'Syria'),
    ('TW', 'Taiwan'),
    ('TJ', 'Tajikistan'),
    ('TZ', 'Tanzania'),
    ('TH', 'Thailand'),
    ('TL', 'Timor-Leste'),
    ('TG', 'Togo'),
    ('TK', 'Tokelau'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad And Tobago'),
    ('TN', 'Tunisia'),
    ('TR', 'Turkiye'),
    ('TM', 'Turkmenistan'),
    ('TC', 'Turks And Caicos'),
    ('TV', 'Tuvalu'),
    ('VI', 'U.s. Virgin Islands'),
    ('UG', 'Uganda'),
    ('UA', 'Ukraine'),
    ('AE', 'United Arab Emirates'),
    ('GB', 'United Kingdom'),
    ('US', 'United States'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistan'),
    ('VU', 'Vanuatu'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnam'),
    ('WF', 'Wallis & Futuna'),
    ('EH', 'Western Sahara'),
    ('YE', 'Yemen'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

CREATE TEMP TABLE country_code_map (old_code TEXT, new_code TEXT, name TEXT);
INSERT INTO country_code_map (old_code, new_code, name) VALUES
    ('AFG', 'AF', 'Afghanistan'),
    ('ALB', 'AL', 'Albania'),
    ('DZA', 'DZ', 'Algeria'),
    ('ASM', 'AS', 'American Samoa'),
    ('AND', 'AD', 'Andorra'),
    ('AGO', 'AO', 'Angola'),
    ('AIA', 'AI', 'Anguilla'),
    ('ATG', 'AG', 'Antigua And Barbuda'),
    ('ARG', 'AR', 'Argentina'),
    ('ARM', 'AM', 'Armenia'),
    ('ABW', 'AW', 'Aruba'),
    ('AUS', 'AU', 'Australia'),
    ('AUT', 'AT', 'Austria'),
    ('BHS', 'BS', 'Bahamas'),
    ('BHR', 'BH', 'Bahrain'),
    ('BGD', 'BD', 'Bangladesh'),
    ('BRB', 'BB', 'Barbados'),
    ('BEL', 'BE', 'Belgium'),
    ('BLZ', 'BZ', 'Belize'),
    ('BEN', 'BJ', 'Benin'),
    ('BMU', 'BM', 'Bermuda'),
    ('BTN', 'BT', 'Bhutan'),
    ('BOL', 'BO', 'Bolivia'),
    ('BIH', 'BA', 'Bosnia And Herzegovina'),
    ('BWA', 'BW', 'Botswana'),
    ('BRA', 'BR', 'Brazil'),
    ('VGB', 'VG', 'British Virgin Islands'),
    ('BRN', 'BN', 'Brunei'),
    ('BFA', 'BF', 'Burkina Faso'),
    ('BDI', 'BI', 'Burundi'),
    ('CPV', 'CV', 'Cabo Verde'),
    ('KHM', 'KH', 'Cambodia'),
    ('CMR', 'CM', 'Cameroon'),
    ('CAN', 'CA', 'Canada'),
    ('CYM', 'KY', 'Cayman Islands'),
    ('CAF', 'CF', 'Central African Republic'),
    ('TCD', 'TD', 'Chad'),
    ('CHL', 'CL', 'Chile'),
    ('COL', 'CO', 'Colombia'),
    ('COM', 'KM', 'Comoros'),
    ('COG', 'CG', 'Congo'),
    ('COK', 'CK', 'Cook Islands'),
    ('CRI', 'CR', 'Costa Rica'),
    ('CIV', 'CI', 'Côte D''Ivoire'),
    ('HRV', 'HR', 'Croatia'),
    ('CUB', 'CU', 'Cuba'),
    ('CUW', 'CW', 'Curaçao'),
    ('CYP', 'CY', 'Cyprus'),
    ('CZE', 'CZ', 'Czech Republic (Czechia)'),
    ('DNK', 'DK', 'Denmark'),
    ('DJI', 'DJ', 'Djibouti'),
    ('DMA', 'DM', 'Dominica'),
    ('DOM', 'DO', 'Dominican Republic'),
    ('COD', 'CD', 'Dr Congo'),
    ('ECU', 'EC', 'Ecuador'),
    ('SLV', 'SV', 'El Salvador'),
    ('GNQ', 'GQ', 'Equatorial Guinea'),
    ('ERI', 'ER', 'Eritrea'),
    ('EST', 'EE', 'Estonia'),
    ('SWZ', 'SZ', 'Eswatini'),
    ('ETH', 'ET', 'Ethiopia'),
    ('FRO', 'FO', 'Faeroe Islands'),
    ('FLK', 'FK', 'Falkland Islands'),
    ('FJI', 'FJ', 'Fiji'),
    ('FIN', 'FI', 'Finland'),
    ('PYF', 'PF', 'French Polynesia'),
    ('GAB', 'GA', 'Gabon'),
    ('GMB', 'GM', 'Gambia'),
    ('GEO', 'GE', 'Georgia'),
    ('DEU', 'DE', 'Germany'),
    ('GHA', 'GH', 'Ghana'),
    ('GIB', 'GI', 'Gibraltar'),
    ('GRL', 'GL', 'Greenland'),
    ('GRD', 'GD', 'Grenada'),
    ('GUM', 'GU', 'Guam'),
    ('GTM', 'GT', 'Guatemala'),
    ('GIN', 'GN', 'Guinea'),
    ('GNB', 'GW', 'Guinea-Bissau'),
    ('GUY', 'GY', 'Guyana'),
    ('HTI', 'HT', 'Haiti'),
    ('VAT', 'VA', 'Holy See'),
    ('HND', 'HN', 'Honduras'),
    ('HUN', 'HU', 'Hungary'),
    ('ISL', 'IS', 'Iceland'),
    ('IRN', 'IR', 'Iran'),
    ('IRQ', 'IQ', 'Iraq'),
    ('IRL', 'IE', 'Ireland'),
    ('IMN', 'IM', 'Isle Of Man'),
    ('ISR', 'IL', 'Israel'),
    ('JAM', 'JM', 'Jamaica'),
    ('KAZ', 'KZ', 'Kazakhstan'),
    ('KEN', 'KE', 'Kenya'),
    ('KIR', 'KI', 'Kiribati'),
    ('KWT', 'KW', 'Kuwait'),
    ('KGZ', 'KG', 'Kyrgyzstan'),
    ('LAO', 'LA', 'Laos'),
    ('LVA', 'LV', 'Latvia'),
    ('LBN', 'LB', 'Lebanon'),
    ('LSO', 'LS', 'Lesotho'),
    ('LBR', 'LR', 'Liberia'),
    ('LBY', 'LY', 'Libya'),
    ('LIE', 'LI', 'Liechtenstein'),
    ('LTU', 'LT', 'Lithuania'),
    ('LUX', 'LU', 'Luxembourg'),
    ('MAC', 'MO', 'Macao'),
    ('MDG', 'MG', 'Madagascar'),
    ('MWI', 'MW', 'Malawi'),
    ('MDV', 'MV', 'Maldives'),
    ('MLI', 'ML', 'Mali'),
    ('MLT', 'MT', 'Malta'),
    ('MHL', 'MH', 'Marshall Islands'),
    ('MRT', 'MR', 'Mauritania'),
    ('MUS', 'MU', 'Mauritius'),
    ('MYT', 'YT', 'Mayotte'),
    ('MEX', 'MX', 'Mexico'),
    ('FSM', 'FM', 'Micronesia'),
    ('MDA', 'MD', 'Moldova'),
    ('MCO', 'MC', 'Monaco'),
    ('MNG', 'MN', 'Mongolia'),
    ('MNE', 'ME', 'Montenegro'),
    ('MSR', 'MS', 'Montserrat'),
    ('MAR', 'MA', 'Morocco'),
    ('MOZ', 'MZ', 'Mozambique'),
    ('NAM', 'NA', 'Namibia'),
    ('NRU', 'NR', 'Nauru'),
    ('NPL', 'NP', 'Nepal'),
    ('NLD', 'NL', 'Netherlands'),
    ('NCL', 'NC', 'New Caledonia'),
    ('NIC', 'NI', 'Nicaragua'),
    ('NER', 'NE', 'Niger'),
    ('NGA', 'NG', 'Nigeria'),
    ('NIU', 'NU', 'Niue'),
    ('PRK', 'KP', 'North Korea'),
    ('MKD', 'MK', 'North Macedonia'),
    ('MNP', 'MP', 'Northern Mariana Islands'),
    ('NOR', 'NO', 'Norway'),
    ('OMN', 'OM', 'Oman'),
    ('PLW', 'PW', 'Palau'),
    ('PAN', 'PA', 'Panama'),
    ('PNG', 'PG', 'Papua New Guinea'),
    ('PRY', 'PY', 'Paraguay'),
    ('PER', 'PE', 'Peru'),
    ('PHL', 'PH', 'Philippines'),
    ('PRT', 'PT', 'Portugal'),
    ('PRI', 'PR', 'Puerto Rico'),
    ('QAT', 'QA', 'Qatar'),
    ('REU', 'RE', 'Réunion'),
    ('ROU', 'RO', 'Romania'),
    ('RUS', 'RU', 'Russia'),
    ('RWA', 'RW', 'Rwanda'),
    ('BLM', 'BL', 'Saint Barthelemy'),
    ('SHN', 'SH', 'Saint Helena'),
    ('KNA', 'KN', 'Saint Kitts & Nevis'),
    ('LCA', 'LC', 'Saint Lucia'),
    ('MAF', 'MF', 'Saint Martin'),
    ('SPM', 'PM', 'Saint Pierre & Miquelon'),
    ('WSM', 'WS', 'Samoa'),
    ('SMR', 'SM', 'San Marino'),
    ('STP', 'ST', 'Sao Tome & Principe'),
    ('SAU', 'SA', 'Saudi Arabia'),
    ('SEN', 'SN', 'Senegal'),
    ('SRB', 'RS', 'Serbia'),
    ('SLE', 'SL', 'Sierra Leone'),
    ('SXM', 'SX', 'Sint Maarten'),
    ('SVK', 'SK', 'Slovakia'),
    ('SVN', 'SI', 'Slovenia'),
    ('SLB', 'SB', 'Solomon Islands'),
    ('SOM', 'SO', 'Somalia'),
    ('SSD', 'SS', 'South Sudan'),
    ('ESP', 'ES', 'Spain'),
    ('VCT', 'VC', 'St. Vincent & Grenadines'),
    ('PSE', 'PS', 'State Of Palestine'),
    ('SDN', 'SD', 'Sudan'),
    ('SUR', 'SR', 'Suriname'),
    ('SWE', 'SE', 'Sweden'),
    ('CHE', 'CH', 'Switzerland'),
    ('SYR', 'SY', 'Syria'),
    ('TJK', 'TJ', 'Tajikistan'),
    ('TZA', 'TZ', 'Tanzania'),
    ('TLS', 'TL', 'Timor-Leste'),
    ('TGO', 'TG', 'Togo'),
    ('TKL', 'TK', 'Tokelau'),
    ('TON', 'TO', 'Tonga'),
    ('TTO', 'TT', 'Trinidad And Tobago'),
    ('TKM', 'TM', 'Turkmenistan'),
    ('TCA', 'TC', 'Turks And Caicos'),
    ('TUV', 'TV', 'Tuvalu'),
    ('VIR', 'VI', 'U.s. Virgin Islands'),
    ('UGA', 'UG', 'Uganda'),
    ('ARE', 'AE', 'United Arab Emirates'),
    ('URY', 'UY', 'Uruguay'),
    ('UZB', 'UZ', 'Uzbekistan'),
    ('VUT', 'VU', 'Vanuatu'),
    ('WLF', 'WF', 'Wallis & Futuna'),
    ('ESH', 'EH', 'Western Sahara'),
    ('YEM', 'YE', 'Yemen'),
    ('ZMB', 'ZM', 'Zambia'),
    ('ZWE', 'ZW', 'Zimbabwe');

UPDATE exhibitors e SET country_code = m.new_code FROM country_code_map m WHERE e.country_code = m.old_code;
UPDATE exhibitors e SET billing_country_code = m.new_code FROM country_code_map m WHERE e.billing_country_code = m.old_code;
UPDATE agents a SET country_code = m.new_code FROM country_code_map m WHERE a.country_code = m.old_code;
UPDATE companies c SET country_code = m.new_code FROM country_code_map m WHERE c.country_code = m.old_code;
UPDATE groups g SET country_code = m.new_code FROM country_code_map m WHERE g.country_code = m.old_code;

DELETE FROM countries c USING country_code_map m WHERE c.code = m.old_code;

DROP TABLE country_code_map;
